apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iot-part-3
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    path: p3/manifest
    repoURL: https://github.com/RNCP7/Inception-of-Things
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      enabled: true