Vagrant.configure("2") do |config|
    config.vm.box = "generic/alpine318"
    config.vm.box_version = "4.3.12"

    config.vm.synced_folder ".", "/vagrant", type: "virtualbox", SharedFoldersEnableSymlinksCreate: false

    config.vm.define "lseillerS" do |server|
        server.vm.hostname = "lseillerS"
        server.vm.network "private_network", ip: "192.168.56.110"
        server.vm.network "forwarded_port", guest: 443, host: 443
        server.vm.provider "virtualbox" do |v|
            v.memory = 8192
            v.cpus = 4
            v.name = "lseillerS"
        end
        server.vm.provision "shell", path: "provisions/install-k3s-server.sh"
    end
end
