Vagrant.configure("2") do |config|
    config.vm.box = "generic/alpine318"
    config.vm.box_version = "4.3.12"

    config.vm.define "hperrinS" do |server|
        server.vm.hostname = "hperrinS"
        server.vm.network "private_network", ip: "192.168.56.110"
        server.vm.provider "libvirt" do |v|
            v.memory = 1024
            v.cpus = 1
            v.driver = "qemu"
        end
        server.vm.provision "shell", path: "provisions/install-k3s-server.sh", env: {"KUBECONFIG": "~/config/config.yaml"}
        server.vm.provision "shell", path: "provisions/uninstall-k3s.sh", name: "uninstall-k3s", run: "never"
        #server.vm.provision "file", source: "config/config.yaml", destination: "/etc/rancher/k3s/config.yaml"
    end

    config.vm.define "hperrinSW" do |worker|
        worker.vm.hostname = "hperrinSW"
        worker.vm.network "private_network", ip: "192.168.56.111"
        worker.vm.provider "libvirt" do |v|
            v.memory = 1024
            v.cpus = 1
            v.driver = "qemu"
        end
        worker.vm.provision "shell", path: "provisions/install-k3s-agent.sh", env: {"KUBECONFIG": "~/config/config.yaml"}
        worker.vm.provision "shell", path: "provisions/uninstall-k3s.sh", name: "uninstall-k3s", run: "never"
        #worker.vm.provision "file", source: "config/config.yaml", destination: "/etc/rancher/k3s/config.yaml"
    end
end
